apiVersion: v1
kind: Service
metadata:
  name: node-lb-service
  labels:
    app: nodeapp
spec:
  ports:
    - protocol : TCP
      port: 80
      targetPort: 8000

  selector:
    app: nodeapp
  type: LoadBalancer